#!/usr/bin/env bash
#
# git_push_pr.sh - Push commits to new remote branch and create PR/MR.
# Called AFTER AI has amended the commit message.
#
# Usage:
#   bash git_push_pr.sh [--target <branch>]
#
# Output (key=value pairs for AI to parse):
#   PLATFORM=github|gitlab
#   PR_URL=<url>
#   PR_NUMBER=<number>
#   NEW_BRANCH=<branch>
#   TARGET_BRANCH=<branch>
#   DIFF_FILE=<path>
#   STAT_FILE=<path>
#
set -euo pipefail

info()  { echo "[INFO] $*"; }
warn()  { echo "[WARN] $*"; }
error() { echo "[ERROR] $*" >&2; }
ok()    { echo "[OK] $*"; }

# ========== Args ==========
TARGET_BRANCH=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --target) TARGET_BRANCH="$2"; shift 2 ;;
        *) error "Unknown option: $1"; exit 1 ;;
    esac
done

# ========== Pre-checks ==========
if ! git rev-parse --is-inside-work-tree &>/dev/null; then
    error "Not inside a git repository."
    exit 1
fi

cd "$(git rev-parse --show-toplevel)"

# ========== Detect platform ==========
REMOTE_URL=$(git remote get-url origin 2>/dev/null || echo "")
if [[ -z "$REMOTE_URL" ]]; then
    error "No origin remote detected."
    exit 1
fi

if echo "$REMOTE_URL" | grep -qiE "github\.com"; then
    PLATFORM="github"
else
    PLATFORM="gitlab"
fi
info "Platform: $PLATFORM"

# Check CLI
if [[ "$PLATFORM" == "github" ]]; then
    command -v gh &>/dev/null || { error "gh CLI not installed. See: https://cli.github.com/"; exit 1; }
    gh auth status &>/dev/null 2>&1 || { error "gh CLI not authenticated. Run: gh auth login"; exit 1; }
else
    command -v glab &>/dev/null || { error "glab CLI not installed. See: https://gitlab.com/gitlab-org/cli"; exit 1; }
    glab auth status &>/dev/null 2>&1 || { error "glab CLI not authenticated. Run: glab auth login"; exit 1; }
fi

# ========== Detect target branch ==========
if [[ -z "$TARGET_BRANCH" ]]; then
    TARGET_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@' || echo "")
    if [[ -z "$TARGET_BRANCH" ]]; then
        for b in main master; do
            if git show-ref --verify --quiet "refs/remotes/origin/$b" 2>/dev/null; then
                TARGET_BRANCH="$b"
                break
            fi
        done
    fi
    if [[ -z "$TARGET_BRANCH" ]]; then
        error "Cannot detect default branch. Use --target to specify."
        exit 1
    fi
fi

# ========== Check unpushed commits ==========
UNPUSHED=$(git log "origin/$TARGET_BRANCH..HEAD" --oneline 2>/dev/null | wc -l | tr -d ' ')
if [[ "$UNPUSHED" -eq 0 ]]; then
    warn "No unpushed commits. Nothing to push."
    exit 0
fi

info "Found $UNPUSHED unpushed commit(s)."

# Get commit message for PR title
COMMIT_MSG=$(git log -1 --pretty=%s)
info "Commit message: $COMMIT_MSG"

# ========== Export diff ==========
MAX_DIFF_LINES=50000

DIFF_FILE=$(mktemp /tmp/git_pr_diff_XXXXXX.txt)
STAT_FILE=$(mktemp /tmp/git_pr_stat_XXXXXX.txt)

git diff "origin/$TARGET_BRANCH"..HEAD --stat > "$STAT_FILE"
DIFF_DETAIL=$(git diff "origin/$TARGET_BRANCH"..HEAD)
echo "$DIFF_DETAIL" | head -"$MAX_DIFF_LINES" > "$DIFF_FILE"

DIFF_LINES=$(echo "$DIFF_DETAIL" | wc -l | tr -d ' ')
if [[ "$DIFF_LINES" -gt "$MAX_DIFF_LINES" ]]; then
    info "Diff truncated: $DIFF_LINES -> $MAX_DIFF_LINES lines"
    echo -e "\n... (truncated, $DIFF_LINES total lines)" >> "$DIFF_FILE"
fi

CHANGED_FILES=$(cat "$STAT_FILE" | head -30)

# ========== Push to new remote branch ==========
TIMESTAMP=$(date +%Y%m%d%H%M%S)
NEW_BRANCH="auto-pr-${TIMESTAMP}"

info "Pushing to remote branch: $NEW_BRANCH"
if ! git push origin "HEAD:refs/heads/$NEW_BRANCH" 2>&1; then
    error "Push failed. Check config and network."
    exit 1
fi

info "Local commits preserved. Run 'git pull' after PR is merged."

# ========== Create PR/MR ==========
PR_TITLE="$COMMIT_MSG"
PR_BODY=$(printf "## Changes\n\n### Files Changed\n\`\`\`\n%s\n\`\`\`\n\n> Auto-generated by git-pr. Detailed description will be updated shortly." "$CHANGED_FILES")

PR_NUMBER=""
PR_URL=""

if [[ "$PLATFORM" == "github" ]]; then
    info "Creating Pull Request..."
    BODY_FILE=$(mktemp /tmp/git_pr_body_XXXXXX.md)
    printf "%s" "$PR_BODY" > "$BODY_FILE"

    PR_URL=$(gh pr create \
        --base "$TARGET_BRANCH" \
        --head "$NEW_BRANCH" \
        --title "$PR_TITLE" \
        --body-file "$BODY_FILE" 2>&1) || {
        error "PR creation failed: $PR_URL"
        rm -f "$BODY_FILE"
        exit 1
    }
    rm -f "$BODY_FILE"
    PR_NUMBER=$(echo "$PR_URL" | grep -oE '/pull/[0-9]+' | grep -oE '[0-9]+' || echo "")
else
    info "Creating Merge Request..."
    MR_OUTPUT=$(glab mr create \
        --source-branch "$NEW_BRANCH" \
        --target-branch "$TARGET_BRANCH" \
        --title "$PR_TITLE" \
        --description "$PR_BODY" \
        --remove-source-branch \
        -y 2>&1) || {
        error "MR creation failed: $MR_OUTPUT"
        exit 1
    }
    PR_URL=$(echo "$MR_OUTPUT" | grep -oE 'https?://[^ ]+' | head -1)
    [[ -z "$PR_URL" ]] && PR_URL="$MR_OUTPUT"
    PR_NUMBER=$(echo "$PR_URL" | grep -oE 'merge_requests/[0-9]+' | grep -oE '[0-9]+' || echo "")
fi

# ========== Output ==========
echo ""
echo "============================================"
echo "  GIT-PR RESULT"
echo "============================================"
echo ""
ok "PR/MR created successfully!"
echo ""
echo "PLATFORM=$PLATFORM"
echo "PR_URL=$PR_URL"
echo "PR_NUMBER=$PR_NUMBER"
echo "NEW_BRANCH=$NEW_BRANCH"
echo "TARGET_BRANCH=$TARGET_BRANCH"
echo "DIFF_FILE=$DIFF_FILE"
echo "STAT_FILE=$STAT_FILE"
echo ""
echo "============================================"
